# Generated by Django 4.2.10 on 2024-08-17 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_group_subscription'),
        ('users', '0006_alter_subscription_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='courses.group', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
