# Generated by Django 4.2.10 on 2024-08-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_subscription_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='group',
        ),
    ]
