# Generated by Django 4.2.10 on 2024-08-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_group_subscription'),
        ('users', '0008_remove_subscription_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_group', to='courses.group', verbose_name='Группа')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions_group', to='users.subscription', verbose_name='Подписка')),
            ],
        ),
    ]
