# Generated by Django 4.2.10 on 2024-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_group_course_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
    ]
