# Generated by Django 4.2.10 on 2024-08-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_course_alter_subscription_user'),
        ('courses', '0005_course_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AddField(
            model_name='group',
            name='subscription',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='users.subscription', verbose_name='Подписка пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
