# Generated by Django 4.2.10 on 2024-08-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_course_alter_subscription_user'),
        ('courses', '0006_remove_group_user_group_subscription_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.subscription', verbose_name='Подписка пользователя'),
        ),
    ]
