# Generated by Django 4.2.10 on 2024-08-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_subscription_group'),
        ('courses', '0008_remove_group_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.subscription', verbose_name='Подписки'),
            preserve_default=False,
        ),
    ]
