# Generated by Django 4.2.10 on 2024-08-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_group_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subscription',
        ),
    ]
